---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: git-repo
spec:
  type: git
  params:
    - name: url
      value: https://github.com/Divyansh42/simple-golang-webserver
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: image
spec:
  type: image
  params:
    - name: url
      value: image-registry.openshift-image-registry.svc:5000/simple-golang-app/simple-golang-webserver:latest
