apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: update-deployment-taskrun
spec:
  taskRef:
    name: update-deployment
  inputs:
    params:
      - name: deployment
        value: simple-golang-app
    resources:
      - name: image
        resourceSpec:
          type: image
          params:
            - name: url
              value: image-registry.openshift-image-registry.svc:5000/simple-golang-app/simple-golang-webserver:latest
